//
//  NewsItem.swift
//  Crammerock-ios-app
//
//  Created by Jorgé Reyniers on 10/08/2019.
//  Copyright © 2019 Jorgé Reyniers. All rights reserved.
//

import Foundation

struct NewsItem {
    var imageName: String
    var title: String
    var body: String
    var publicationDate: Date
    
    init(imageName: String, title: String, body: String, publicationDate: Date) {
        self.imageName = imageName
        self.title = title
        self.body = body
        self.publicationDate = publicationDate
    }
    
    static func loadNewsItems() -> [NewsItem] {
        return [
            NewsItem(imageName: "uitverkocht", title: "Sold out - Complet - Uitverkocht", body: "Het is gebeurd! De 29ste editie van Crammerock is compleet uitverkocht. Alle vrijdag-, zaterdag-, weekend- en campingtickets zijn de deur uit. Wie geen ticket heeft kunnen bemachtigen moeten we helaas teleurstellen.\n\n Volg de updates over het festival op de voet via Facebook en Instagram.\n\n Jong geleerd is oud gedaan! Voor kinderen die tijdens Crammerock jonger zijn dan 12 jaar vragen we een bijdrage van 5 euro. Concreet: kinderen die geboren zijn na 6 september 2007 moet dus ook een ticket hebben. De opbrengst van deze tickets gaat tijdens De Warmste Week naar een goed doel. Wie zijn kids wil registreren kan dat via http://bit.ly/2GCkQS6.\n\n Ondanks het wettelijk kader tiert de handel in festivaltickets op de secundaire markt welig. Al te vaak wordt er vastgesteld dat er gefraudeerde tickets worden aangeboden op de zwarte markt en die geven geen garantie tot geldigheid. De kans bestaat dus dat het ticket gekocht via de secundaire markt geblacklist is en bijgevolg zal de toegang tot het festival geweigerd worden. Meer info hierover op www.ilovemyticket.be en via FOD Economie.", publicationDate: DateHelper.createDate(day: 28, month: 7, year: 2019, hour: 12, minutes: 00)),
            NewsItem(imageName: "skunkanansie", title: "12 nieuwe namen voor Crammerock 2019!", body: "Crammerock lost vandaag in één klap 12 nieuwe namen. Met de toevoeging van Skunk Anansie, K’s Choice, Dean Lewis, Stef Kamil Carlens & band, IBE, SaSaSas en nog vele andere rock-, pop-, hiphop- en dance-acts belooft Crammerock weer één groot feest te worden. Heb jij je tickets al? Want de laatste weekend- en zaterdagtickets vliegen op dit moment de deur uit.\n\n Op vrijdag 6 september wordt de Crammerock-affiche aangevuld met Stef Kamil Carlens & band, de Britse rockers van The Sherlocks, de doorgewinterde Gentse dj/producer Maxim Lany, het opkomende melodieuze techno-duo Joyhauser, StuBru-icoon DJ Licious en Stijn Van De Voorde & (Equal Idiot) Thibault Christiaensen.\n\n Skunk Anansie is de grootste klepper die op zaterdag wordt toegevoegd aan de line-up. Hebben ook bevestigd voor zaterdag: K’s Choice, de immens populaire Australische singer-songwriter Dean Lewis, 'The Voice'-revelatie IBE, drum & bass-kanon Kanine en de vierkoppige Britse d&b-knallers van SaSaSas.", publicationDate: DateHelper.createDate(day: 14, month: 7, year: 2019, hour: 12, minutes: 00)),
            NewsItem(imageName: "balthazar", title: "Extra festivalshow voor Balthazar na triomf in Werchter", body: "Groot nieuws! We hebben voor jullie Balthazar kunnen strikken voor een exclusief concert. Want na Rock Werchter spelen deze publiekslievelingen deze zomer nog maar één keer op Belgische bodem, jawel, op Crammerock!\n\n De recensies van hun optreden op Rock Werchter zijn alvast veelbelovend voor hun show op zaterdag 7 september in Stekene.\n\n 'Balthazar op Rock Werchter: werkelijk niks op aan te merken' ★★★★★ - DE MORGEN\n\n 'Straf Balthazar overtuigt Werchter ook met nieuw werk' ★★★★ - HET NIEUWSBLAD\n\n 'Balthazar: Bloed, Bier, Bongo's' ★★★★ - DE STANDAARD\n\n Wie er op vrijdag 6 en zaterdag 7 september bij wil zijn, wacht best niet te lang met het kopen van zijn tickets. Op dit moment zijn reeds 2/3de van de beschikbare tickets de deur uit. De afgelopen acht jaren was Crammerock helemaal uitverkocht.", publicationDate: DateHelper.createDate(day: 1, month: 7, year: 2019, hour: 12, minutes: 00)),
            NewsItem(imageName: "jungle", title: "Crammerock 2019 wordt nog straffer met deze zes nieuwe bands!", body: "We voegen nog maar eens 6 straffe namen toe aan de al goed gevulde affiche. De zalige zomerse hits van funkband Jungle en de razend populaire dj/producer Jonas Blue zullen het festival omtoveren tot één groot feest. Naast deze Britse toppers kondigt Crammerock ook de komst aan van deze Belgische acts: new wave-sensatie Whispering Sons, de afscheidnemende heren van The Van Jets, de garagerockers van Black Leather Jacket en rijzende hiphopster Miss Angel.\n\n Tickets zijn te koop via www.crammerock.be/tickets.", publicationDate: DateHelper.createDate(day: 28, month: 6, year: 2019, hour: 12, minutes: 00)),
            NewsItem(imageName: "hiphopknallers", title: "12 nieuwe hiphop en elektropop knallers!", body: "Hiphop en elektropop: Deze 12 nieuwe knallers komen naar Crammerock Crammerock lost vandaag in één keer twaalf (12!) nieuwe namen. Dit keer trekken we een blik hiphop- en elektropop-acts open. Wat denk je van Ronnie Flex & Deuxperience, Ares, Frenna, Yung Felix, The Blockparty, Leafs, Yung Mavu, Woodie Smalls, Black Mamba en K1D? Of van de OT en Tessa Dixson? Feestje!\n\n Door de toevoeging van deze nieuwe namen zijn intussen 23 namen bekend. De komende weken zullen we nog een reeks namen droppen, want ook dit jaar komen er weer zo’n 50 top-acts uit de rock, pop, dance, elektro en hiphop naar Crammerock.", publicationDate: DateHelper.createDate(day: 17, month: 6, year: 2019, hour: 12, minutes: 00)),
            NewsItem(imageName: "warhola", title: "Drie keer Belgisch: Glints - Sons - Warhola", body: "Een nieuwe week, een nieuwe rist namen voor Crammerock 2019. Dit keer hebben we drie verse Vlaamse maatjes in de aanbieding: Warhola, Glints en SONS. Voor elk wat wils dus: frêle elektronica, verdomd slimme hiphop en dampende garagerock. Intussen zijn 11 straffe acts bekend, voor 6 en 7 september. Nog een slik veertigtal te gaan.\n\n Goed nieuws voor de fans van het muzikale brein achter Bazart: Oliver Symons komt ook met Warhola, zijn andere band, naar Crammerock. Vijf jaar nadat Symons met Warhola Humo’s Rock Rally heeft gewonnen, heeft Symons net zijn debuutplaat geperst: “Young loving”.  Die bulkt van de elektronica, gemengd met een scheut melancholische pop. Op Crammerock-vrijdag brengt Symons 2 drummers en 2 synth-spelers mee die de sound van Warhola live extra punch geven.\n\n Warhola werkte voor één track op zijn debuutplaat samen met een andere Crammerock-artiest: Glints, de hiphopband van Antwerpenaar Jan Maarschalk Lemmens, die hiphop overgiet met een lekker sausjes elektronica en pop. Vaak smaakt dat lekker smooth, maar op de hitsingle 'Bugatti', laat J-M merken dat hij ook spicy uit de hoek kan komen. Glints speelt ten dans op zaterdag 7 september.\n\n Wie altijd pittig uit de hoek komen, zijn de kerels van SONS. Deze garagepunkrockers uit het naburige Melsele spelen een quasi-thuismatch op het fermste festival van het Waasland. Vorig jaar speelden deze polderzonen op zowat elk festival dat ertoe doet. Ook ons tentzeil lieten ze vorige zomer duchtig wapperen. Omdat ze dat zo voorbeeldig deden, mogen ze dat kunstje nog eens dubbeldik komen overdoen, op Crammerock-zaterdag.\n\n Tickets voor Crammerock zijn sinds 10 dagen te koop via de online ticketshop op crammerock.be. De kaartjesverkoop heeft sindsdien een vliegende start genomen. Wie er op vrijdag 6 en zaterdag 7 september bij wil wil zijn, wacht best niet te lang met het kopen van zijn tickets. De afgelopen acht jaren was Crammerock namelijk helemaal uitverkocht.\n\n Omdat Crammerock zich ook dit jaar weer wil onderscheiden met lage ticketprijzen, houden we de prijzen van vorig jaar aan: 60,32 euro voor een weekendticket (€58 basis + €2,32 servicekosten) en 38,48 euro voor een dagticket (€37 basis + €1,48 servicekosten).\n\n Daarmee geeft Crammerock de festivalbezoeker waar voor z’n geld, want ook dit jaar komen er weer zo’n 50 top-acts uit de rock, pop, dance, elektro en hiphop naar Stekene.\n\n De afgelopen weken loste Crammerock al met mondjesmaat namen voor de 29ste editie van het festival: Craig David, The Vaccines, Bazart, Black Box Revelation, Goose, Enter Shikari, Lil Kleine en Circa Waves. En nu dus ook Warhola, Glints en Sons. De komende tijd zal de festivalorganisatie dus nog een flinke stapel namen bekendmaken.", publicationDate: DateHelper.createDate(day: 3, month: 6, year: 2019, hour: 12, minutes: 00)),
            NewsItem(imageName: "luchtfoto", title: "Dit moet je weten over de ticketverkoop", body: "Tickets voor Crammerock 2019 zijn te koop vanaf 25 mei om 14u via deze website.\n\n Opgelet! Dit jaar worden er geen tickets meer verkocht via onze lokale verkooppunten. De enige plaats waar je tickets kan kopen is in de ticketshop op deze website.\n\n Een Weekendticket kost net als vorig jaar 60,32 euro. (€58 BASIS + €2,32 SERVICEKOSTEN)\n Een Dagticket voor Vrijdag kost dit jaar 38,48 euro. (€37 BASIS + €1,48 SERVICEKOSTEN)\n Een Dagticket voor Zaterdag kost dit jaar 38,48 euro. (€37 BASIS + €1,48 SERVICEKOSTEN)\n Een Campingticket kost dit jaar 15,60 euro. (€15 Basis + €0,60 SERVICEKOSTEN)\n Een Kidsticket kost dit jaar 5 euro. (De opbrengst gaat integraal naar een goed doel)\n Ook dit jaar kan je opnieuw drankvouchers kopen aan voordeelprijs. Een voucher voor 16 bonnen kost €37,44 (€36 Basis + €1,44 SERVICEKOSTEN)", publicationDate: DateHelper.createDate(day: 22, month: 5, year: 2019, hour: 12, minutes: 00))
        ]
    }
    
}
